//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.34209
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LHDB_SH_Core.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LHDB_SH_Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Report {
            get {
                object obj = ResourceManager.GetObject("Report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 學生資料名冊樣板_國教署主管學校_ {
            get {
                object obj = ResourceManager.GetObject("學生資料名冊樣板_國教署主管學校_", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 學生資料名冊樣板_非國教署主管學校_ {
            get {
                object obj = ResourceManager.GetObject("學生資料名冊樣板_非國教署主管學校_", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 定期考查成績名冊樣板 {
            get {
                object obj = ResourceManager.GetObject("定期考查成績名冊樣板", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 成績名冊樣版 {
            get {
                object obj = ResourceManager.GetObject("成績名冊樣版", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 在產生報表前請先進行以下確認：
        ///1.學生的「學期對照表」是否完整。
        ///路徑：學生身上的「學期對照表」資料項目。
        ///說明：在產生報表時會依學生個人的「學期對照表」比對學生當時的「年級」、「班級」及「科目」資訊。
        ///
        ///2.「班級代碼表」是否已設定。
        ///路徑：學生&gt;學習歷程資料&gt;設定&gt;班級代碼。
        ///
        ///3.「科別對照表」是否正確。
        ///路徑：教務作業&gt;基本設定&gt;管理&gt;科別對照管理。
        ///
        ///4.「部別及班別代碼對照」是否已設定。
        ///路徑：本操作畫面中的「特殊類別對照」，若您學生的「部別」及「班別」相同，您可直接於本操作畫面中的「部別代碼預設值」及「班別代碼預設定」中直接設定。
        ///
        ///操作說明：
        ///請選取欲產生報表之學年度學期，之後選取「產生」即可。
        ///相關呈報說明請參考「104學年高級中等學校學生學習歷程資料庫 學生資料名冊」。 的當地語系化字串。
        /// </summary>
        internal static string 畫面說明_學生資料名冊 {
            get {
                return ResourceManager.GetString("畫面說明_學生資料名冊", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 在產生報表前請先進行以下確認：
        ///1.學生的「學期對照表」是否完整。
        ///路徑：學生身上的「學期對照表」資料項目。
        ///說明：在產生報表時會依學生個人的「學期對照表」比對學生當時的「年級」、「班級」及「科目」資訊。
        ///
        ///2.「班級代碼表」是否已設定。
        ///路徑：學生&gt;學習歷程資料&gt;設定&gt;班級代碼。
        ///說明：「修課班級」是由「學期對照表」及本對照表比對而來。
        ///
        ///3.「科別對照表」是否正確。
        ///路徑：教務作業&gt;基本設定&gt;管理&gt;科別對照管理。
        ///
        ///4.「部別及班別代碼對照」是否已設定。
        ///路徑：學生&gt;學習歷程資料&gt;報表&gt;學生資料名冊&gt;「特殊類別對照」。
        ///說明：「修課班級」將來自本對照表。
        ///
        ///操作說明：
        ///請選取欲產生報表之學年度學期與段考別、試別，之後選取「產生」即可。
        ///相關呈報說明請參考「104學年高級中等學校學生學習歷程資料庫 定期考查成績名冊」。 的當地語系化字串。
        /// </summary>
        internal static string 畫面說明_定期考查成績名冊 {
            get {
                return ResourceManager.GetString("畫面說明_定期考查成績名冊", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 在產生報表前請先進行以下確認：
        ///1.學生的「學期對照表」是否完整。
        ///路徑：學生身上的「學期對照表」資料項目。
        ///說明：在產生報表時會依學生個人的「學期對照表」比對學生當時的「年級」、「班級」及「科目」資訊。
        ///
        ///2.「班級代碼表」是否已設定。
        ///路徑：學生&gt;學習歷程資料&gt;設定&gt;班級代碼。
        ///說明：「修課班級」是由「學期對照表」及本對照表比對而來。
        ///
        ///3.「科別對照表」是否正確。
        ///路徑：教務作業&gt;基本設定&gt;管理&gt;科別對照管理。
        ///
        ///4.「部別及班別代碼對照」是否已設定。
        ///路徑：學生&gt;學習歷程資料&gt;報表&gt;學生資料名冊&gt;「特殊類別對照」。
        ///說明：「修課班級」將來自本對照表。
        ///
        ///5.將「學期科目成績」補上「是否補修成績」、「重修學年度」及「重修學期」。
        ///路徑：學生&gt;資料統計&gt;匯出/匯入&gt;成績相關匯出/匯入&gt;匯出/匯入學期科目成績。
        ///說明：
        ///若學生成績為補修成績，請在匯出科目學期成績的Excel檔中的「是否補修成績」欄位補上「是」，後再使用「匯入學期科目成績」功能將成績匯入。
        ///若學生有重修成績，請在匯出科目學期成績的Excel檔中的「重修學年度」與「重修學期」欄位補上重修學年度學期，後再使 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string 畫面說明_成績名冊 {
            get {
                return ResourceManager.GetString("畫面說明_成績名冊", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 在產生報表前請先進行以下確認：
        ///1.學生的「學期對照表」是否完整。
        ///路徑：學生身上的「學期對照表」資料項目。
        ///說明：在產生報表時會依學生個人的「學期對照表」比對學生當時的「年級」、「班級」及「科目」資訊。
        ///
        ///2.「班級代碼表」是否已設定。
        ///路徑：學生&gt;學習歷程資料&gt;設定&gt;班級代碼。
        ///說明：「學習歷程資料庫」與「繁星資料庫」所使用的「班級代碼」相同。
        ///
        ///3.「科別對照表」是否正確。
        ///路徑：教務作業&gt;基本設定&gt;管理&gt;科別對照管理。
        ///
        ///4.「特色班實驗班名稱對照表」是否已設定。
        ///路徑：本操作畫面中的「特色班實驗班名稱對照」。
        ///
        ///操作說明：
        ///請選取欲產生報表之學年度學期，並於「學校種類」區?選學校所有學制後選取「產生」即可。
        ///相關呈報說明請參考「104學年高級中等學校學生學習歷程資料庫 科目名冊」。 的當地語系化字串。
        /// </summary>
        internal static string 畫面說明_科目名冊 {
            get {
                return ResourceManager.GetString("畫面說明_科目名冊", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 科目名冊樣板 {
            get {
                object obj = ResourceManager.GetObject("科目名冊樣板", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 缺勤紀錄名冊樣板 {
            get {
                object obj = ResourceManager.GetObject("缺勤紀錄名冊樣板", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 設定 {
            get {
                object obj = ResourceManager.GetObject("設定", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
